on:
  workflow_run:
    workflows: [Testing Manual Input Variables]
    types: [completed]
env: 
  WORKFLOW_NAME: ${{ github.event.workflow_run.name}}
  WORKFLOW_URL: ${{ github.event.workflow_run.url}}

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: |
            echo 'The triggering workflow passed'
            echo $WORKFLOW_NAME
            echo $WORKFLOW_URL

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'