name: Testing Manual Variables
on:
  workflow_dispatch:
  input:
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"