name: Testing Manual Input Variables
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        options:
        - test
        - prod
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'test' }}

    steps:
      - uses: actions/checkout@v2

      - name: greet test
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
  build-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'prod' }}

    steps:
      - uses: actions/checkout@v2

      - name: greet prod
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
