name: Testing Specific Path Push
on:
  push:
    branches: [main]
    paths:
      - 'test/**'
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: message
        run: |
          git tag | sort -V | tail -1
          echo "It works"
 