name: Testing Release Version
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/testing-release-versions.yml"
  workflow_dispatch:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: message
        run: |
          RELEASE=$(git tag | sort -V | tail -1)
          echo "${RELEASE}"
 