name: Testing Scheduled Run
on:
  #schedule:
  # Every 1 year
  #  - cron: "*/5 * * * *"
  push:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: message
        run: | 
          echo "It works"
 
