name: Testing Scheduled Run
#on:
  schedule:
  # Every 1 year
    - cron: "* * * 1 *"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: message
        run: | 
          echo "It works"
 